---
name: Environment setup and build
on:
  push:
    branches:
      - test-workflow
  workflow_dispatch:

jobs:
  setup-environment:
    runs-on: self-hosted
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Install kas
        run: pip3 install kas

  clone_meta_qcom:
    needs: setup-environment
    runs-on: self-hosted
    steps:
      - name: Clone meta-qcom repo
        run: |
          git clone git@github.com:qualcomm-linux/meta-qcom.git
          cd meta-qcom/ci
      - name: Install kas in meta-qcom/ci
        run: sudo pip3 install kas
      - name: Run kas shell and bitbake
        run: |
          cd meta-qcom/ci
          kas shell qcs9100-ride-sx.yml:qcom-distro.yml
          bitbake qcom-multimedia-proprietary-image
