---
name: Environment setup and build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-environment:
    runs-on: self-hosted
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Environment setup commands
        run: |
          pip install kas

  clone_meta_qcom:
    needs: setup-environment
    runs-on: self-hosted
    steps:
      - name: Install kas
        run:  pip install kas 
      - name: Clone meta-qcom repo
        run: |
          git clone https://github.com/qualcomm-linux/meta-qcom.git -b master
          cd meta-qcom/ci
          ls
          kas shell qcs9100-ride-sx.yml:qcom-distro.yml
          bitbake qcom-multimedia-proprietary-image



